import { FinancialProfile } from "../types/profile";

export const mockFinancialProfile: FinancialProfile = {
  user: {
    id: "user_1",
    firstName: "Alex",
    lastName: "Chen",
    email: "alex.chen@example.com",
    joinDate: "2024-01-15T08:00:00Z",
  },
  accounts: [
    {
      id: "acc_chk_1",
      name: "Everyday Checking",
      institution: "Chase Bank",
      type: "checking",
      balance: 12450.50,
      currency: "USD",
      mask: "3456",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: "acc_sav_1",
      name: "High Yield Savings",
      institution: "Marcus",
      type: "savings",
      balance: 45000.00,
      currency: "USD",
      mask: "9012",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: "acc_cc_1",
      name: "Sapphire Reserve",
      institution: "Chase Bank",
      type: "credit_card",
      balance: -3450.75, // Credit card balance is owed (negative impact on net worth usually, or treated as liability)
      currency: "USD",
      mask: "7890",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: "acc_brk_1",
      name: "Individual Brokerage",
      institution: "Fidelity",
      type: "brokerage",
      balance: 125400.20,
      currency: "USD",
      mask: "4567",
      lastUpdated: new Date().toISOString(),
    }
  ],
  transactions: [
    {
      id: "txn_1",
      accountId: "acc_chk_1",
      date: new Date(Date.now() - 1 * 86400000).toISOString(),
      amount: -45.50,
      merchantName: "Whole Foods",
      category: "Food & Dining",
      isPending: false,
    },
    {
      id: "txn_2",
      accountId: "acc_chk_1",
      date: new Date(Date.now() - 2 * 86400000).toISOString(),
      amount: -120.00,
      merchantName: "Shell Station",
      category: "Auto & Transport",
      isPending: false,
    },
    {
      id: "txn_3",
      accountId: "acc_cc_1",
      date: new Date(Date.now() - 3 * 86400000).toISOString(),
      amount: -12.99,
      merchantName: "Netflix",
      category: "Entertainment",
      isPending: false,
    },
    {
      id: "txn_4",
      accountId: "acc_chk_1",
      date: new Date(Date.now() - 5 * 86400000).toISOString(),
      amount: 4500.00,
      merchantName: "Tech Corp Inc.",
      category: "Income",
      isPending: false,
    },
    {
      id: "txn_5",
      accountId: "acc_cc_1",
      date: new Date(Date.now() - 6 * 86400000).toISOString(),
      amount: -145.20,
      merchantName: "Amazon",
      category: "Shopping",
      isPending: false,
    }
  ],
  investments: [
    {
      id: "inv_1",
      accountId: "acc_brk_1",
      ticker: "AAPL",
      name: "Apple Inc.",
      shares: 150,
      price: 185.50,
      currentValue: 27825.00,
      assetClass: "Equity",
      dayChange: 1.2,
      totalReturn: 45.6,
    },
    {
      id: "inv_2",
      accountId: "acc_brk_1",
      ticker: "VOO",
      name: "Vanguard S&P 500 ETF",
      shares: 200,
      price: 450.25,
      currentValue: 90050.00,
      assetClass: "Equity",
      dayChange: 0.8,
      totalReturn: 12.4,
    },
    {
      id: "inv_3",
      accountId: "acc_brk_1",
      ticker: "BND",
      name: "Vanguard Total Bond Market ETF",
      shares: 105,
      price: 71.67,
      currentValue: 7525.20,
      assetClass: "Fixed Income",
      dayChange: -0.1,
      totalReturn: 2.1,
    }
  ],
  loans: [
    {
      id: "loan_1",
      name: "30-Year Fixed Mortgage",
      provider: "Wells Fargo",
      type: "Mortgage",
      totalAmount: 500000,
      remainingBalance: 425000,
      interestRate: 3.5,
      nextEmiDate: new Date(Date.now() + 15 * 86400000).toISOString(),
      nextEmiAmount: 2245.50,
    },
    {
      id: "loan_2",
      name: "Auto Loan",
      provider: "Chase Auto",
      type: "Auto",
      totalAmount: 35000,
      remainingBalance: 12000,
      interestRate: 4.2,
      nextEmiDate: new Date(Date.now() + 5 * 86400000).toISOString(),
      nextEmiAmount: 580.00,
    }
  ],
  insurance: [
    {
      id: "ins_1",
      provider: "Geico",
      type: "Auto",
      coverageAmount: 100000,
      premiumAmount: 120,
      renewalDate: "2026-10-15T00:00:00Z",
    },
    {
      id: "ins_2",
      provider: "Blue Cross",
      type: "Health",
      coverageAmount: 1000000,
      premiumAmount: 350,
      renewalDate: "2026-12-01T00:00:00Z",
    }
  ],
  taxes: [
    {
      year: 2025,
      totalIncome: 145000,
      estimatedTax: 32000,
      taxPaid: 28000,
      deductions: 12500,
    }
  ]
};
